version: "6.9"

services:
  cli:
    container_name: smoldb-cli
    image: smoldb-img:latest 
    command: ./cli-container.sh
    volumes:
      - ./src/:/smoldb/src/
      - ./Makefile:/smoldb/Makefile
      - ./cli-container.sh:/smoldb/cli-container.sh
