name: GCC Ubuntu

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install gcc cmake ninja-build valgrind
    - name: Compile executable
      run: mkdir build && cd build && cmake -DBUILD_TYPE=release .. && cmake --build .
